major = 1
minor = 0
patch = 2
isAlpha = false
isBeta = true
isNodeProject = false
[[remotes]]
name = "origin"
isPublic = false
group = "github"
[[remotes]]
name = "Fork"
group = "Mirrors"
provider = "github"
branch = "master"
isPublic = true
