major = 3
minor = 17
patch = 10
isAlpha = false
isBeta = true
isNodeProject = true
[[remotes]]
name = "origin"
isPublic = false
group = "github"
[[remotes]]
name = "Fork"
group = "Mirrors"
provider = "github"
branch = "master"
isPublic = true
