major = 3
minor = 19
patch = 0
isAlpha = false
isBeta = true
isNodeProject = true
[[remotes]]
name = "origin"
ispublic = false
group = "github"
isPublic = true
[[remotes]]
name = "Fork"
group = "Mirrors"
provider = "github"
branch = "client"
isPublic = true
